name: gradle application
on: push
jobs:
  build-container:
    name: Build docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number}}
      - name: Build and push to docker hub
        uses: docker/build-push-action@v2
        with:
          context:
          push: true
          repository: radhadeo/javaapp
          tags: radhadeo/javaapp:latest, radhadeo/javaapp:${{ github.run_number }}
  
